site_name: MMST - Python kurs
# site_url:

repo_url: https://github.com/BHFFMMST/python-docs
repo_name: BHFFMMST/python-docs

#
# Theme Settings
#
theme:
  name: material
  logo: assets/images/bhff-favicon.png
  favicon: assets/images/bhff-favicon.png

  features:
    # Navigation
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#setting-up-navigation
    - navigation.tabs
    - navigation.sections
    - navigation.path
    # - navigation.tabs.sticky
    # - navigation.expand

    # Table of contents
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#table-of-contents
    - toc.integrate

    # Search
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#setting-up-site-search    - search.suggest
    - search.suggest
    - search.highlight

    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: bhff
      toggle:
        icon: material/weather-sunny
        name: Prebaci na tamni mod

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Prebaci na svijetli mod

#
# Extra Settings
#
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/BHFFMMST
      name: BHFFMMST GitHub Org

extra_css:
  - assets/css/extra.css

#
# Extensions
#
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark

  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - attr_list

  - admonition
  - footnotes

#
# Navigation
# https://www.mkdocs.org/user-guide/configuration/#nav
#

nav:
  - Uvod: index.md
  - Osnovni koncepti:
      - Uvod: content/basics/index.md
      - Okruženje: content/basics/setup.md
      - Varijable: content/basics/varijable/index.md
      - Operatori: content/basics/operatori/index.md
      - Unos i ispis: content/basics/unos_ispis/index.md
      - If-else naredba: content/basics/If-else naredba/index.md
      - Petlje: content/basics/Petlje/index.md
      - Nizovi: content/basics/Nizovi/index.md
      - Funkcije: content/basics/funkcije/index.md
      - Ponavljanje: content/basics/ponavljanje/index.md
      - Resursi: content/basics/resources.md
  - Napredni koncepti:
      - Uvod: content/intermediate/index.md
      - Okruženje: content/intermediate/setup.md
      - Klase: content/intermediate/Klase/index.md
      - Geteri, seteri i konstruktori: content/intermediate/Konstruktori/index.md
      - Funkcije klasa: content/intermediate/Funkcije klasa/index.md
      - Enkapsulacija i apstrakcija: content/intermediate/enkapsulacija_apstrakcija/index.md
      - Nasljeđivanje i polimorfizam: content/intermediate/nasljedjivanje_polimorfizam/index.md
      - Ponavljanje: content/intermediate/ponavljanje/index.md
      - Resursi: content/intermediate/resources.md
